name: python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: pip install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: black
      run: |
        black --check .
    - name: pytest
      run: |
        pytest
